### ISSUE TITLE
Do these not have `start` and `end`?

### ISSUE THREAD

**Issue by Zodiase** [openskope/Datasets#12]
Just checking if these should have date range placeholders.

https://github.com/openskope/Datasets/blob/49f411416298133e683eab2c0bfc79f4a557eaae/datasets/prism_past_800m/analytics.json#L9

https://github.com/openskope/Datasets/blob/49f411416298133e683eab2c0bfc79f4a557eaae/datasets/prism_past_800m/analytics.json#L13

https://github.com/openskope/Datasets/blob/49f411416298133e683eab2c0bfc79f4a557eaae/datasets/lbda-noaa-22454/analytics.json#L5

**Comment by jterstriep** [comment]
Not sure why but they are there now.
