### ISSUE TITLE
In discover tab, Map Icon text for LBDA references Paleocar and should be referencing LBDA.

### ISSUE THREAD

**Issue by jterstriep** [openskope/Datasets#5]
Fix text in overlays.md to reference LBDA instead of PaleoCAR.

**Comment by kintigh** [comment]
I know you showed us once but i don't know where to do this.

**Comment by jterstriep** [comment]
Fixed.

**Comment by jterstriep** [comment]
Fixed (again) seems to have been lost in a merge.
