### ISSUE TITLE
First column in downloaded timeseries CSV file should in time units

### ISSUE THREAD

**Issue by jterstriep** [openskope/Datasets#9]
_Originally submitted by @tmcphillips_ 

Currently the first column of a downloaded CSV file is titled ‘index’, and the values correspond to the zero-based index of each time point in the series rather than to the time (e.g. year) at that time point. For data sets that are known to be in time units of years, the first column should be named 'year', and the values should reflect the year corresponding to each point in the time series. For the full PaleoCAR run the values in the year column should run from 1 to 2000 (currently the first column is titled 'index' and the values range from 0 to 1999).

If the requests to the timeseries service are posed in terms of years (e.g. by including 'timeResolution=year&timeZero=1' as part of the query line for the PaleoCAR data set), the CSV field in the response from the service automatically will satisfy the above requirements.

**Comment by jterstriep** [comment]
Add the above parameters and I'm now getting an error in the graph generation.

**Comment by tmcphillips** [comment]
Make sure the time range in requests is in terms of years when timeResolution=year.

**Comment by jterstriep** [comment]
The webapp needs to be updated to use years rather than index. The PaleoCAR dataset has been updated.
